import Content from './content.js'

const home = new Content(4)
home.format(0, ['h1', 'p'])
home.format(1, ['p', 'p', 'h2'])
home.format(2, ['h2', 'p', 'p'])
home.format(3, ['h2', 'p'])
home.fill(0, 0, 'Restaraunt Name')
home.fill(0, 1, 'We make good ass food!')
home.fill(1, 0, 'But don\'t take our word for it, here\'s a review')
home.fill(1, 1, '"Indeed, Restaraunt does make good ass food"')
home.fill(1, 2, '- Reviewer')
home.fill(2, 0, 'Timings')
home.fill(2, 1, 'Weekdays: 4pm - 2am')
home.fill(2, 2, 'Weekends: 5pm - 3am')
home.fill(3, 0, 'Location')
home.fill(3, 1, '123 Place, City')

const menu = new Content(3)
menu.format(0, ['h1', 'p'])
menu.format(1, ['h2', 'p', 'p', 'p', 'p'])
menu.format(2, ['h2', 'p', 'p'])
menu.fill(0, 0, 'Menu')
menu.fill(0, 1, 'At Restaraunt, we provide the finest of the finer things!')
menu.fill(1, 0, 'Sandwiches')
menu.fill(1, 1, 'Grilled chicken sandwich')
menu.fill(1, 2, 'Chicken fillet sandwich')
menu.fill(1, 3, 'Club sandwich')
menu.fill(1, 4, 'Vegan sandwich')
menu.fill(2, 0, 'Pizzas')
menu.fill(2, 1, 'Margherita pizza')
menu.fill(2, 2, 'Pepperoni pizza')

const about = new Content(2)
about.format(0, ['h2', 'p'])
about.format(1, ['h2', 'p', 'p', 'p'])
about.fill(0, 0, 'Our mission')
about.fill(0, 1, 'We aim to provide our customers with good ass food')
about.fill(1, 0, 'Contact us')
about.fill(1, 1, 'Phone: (333) 444-7777')
about.fill(1, 2, 'Address: 123 Place, City')
about.fill(1, 3, 'Post code: 66200')

export default [home, menu, about]